#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  9 22:36:53 2020

@author: heiko.langer
"""


import cv2
import os

image_folder = '/Users/heiko.langer/deep_dream_fun/neue_pics'
video_name = 'video_new_4.avi'

images = [img for img in os.listdir(image_folder) if img.endswith(".jpg")]
#os.renames(str(word), str.split(word, 'dream_image_out'))

    
#os.renames(image_folder + '/' + images[1], image_folder +'/' + str.split(images[1],'dream_image_out')[1])

images=sorted(images)



#os.renames(image_folder + '/' + word, image_folder +'/' + str.split(word,'dream_image_out')[1])

frame = cv2.imread(os.path.join(image_folder, images[0]))
height, width, layers = frame.shape

video = cv2.VideoWriter(video_name, 0, 4, (width,height))

for image in images:
    video.write(cv2.imread(os.path.join(image_folder, image)))

cv2.destroyAllWindows()
video.release()